### ISSUE TITLE
ttys0 to ttys5

### ISSUE THREAD

**Issue by Alex0161** [GNSSOEM/UM980_RPI_Hat_RtkBase#4]
how can you change ttys0 to ttys5 for orenge pi to connect um980?

**Comment by Jef239** [comment]
You can change ttys0 to ttys5 in the settings of the main service in the Web interface. This will give you everything except auto-detection of the device.

For auto-detection, you need to find the UnicoreConfigure.sh file in the Install directory. Inside it, in the detect_uart procedure, you need to find the line “for port in ttyAMA5 ttyAMA4 ttyAMA3 ttyAMA2 ttyAMA1 ttyAMA0 ttyS0 serial0; do” and add ttyS5 there.

After that, from the Install directory, run create_release.sh to create install.sh

**Comment by Jef239** [comment]
I do it in the next version, after current release

**Comment by Jef239** [comment]
Done

**Comment by Jef239** [comment]
Done
