### ISSUE TITLE
Cant get rtcm1013

### ISSUE THREAD

**Issue by juffe84** [GNSSOEM/UM980_RPI_Hat_RtkBase#7]
Hello.
I cant get rtcm1013 message from the stream. Why? Using UM980 board from gnnstore.
Also I cant change antenna type ELT0123 to ADVNULLANTENNA. What is proper way to change it?

**Comment by Jef239** [comment]
> Hello. I cant get rtcm1013 message from the stream. Why? 

What is your UM980 firmware version? In R4.10Build10231 I get 1013, although even in the latest documentation it is not described.

>Also I cant change antenna type ELT0123 to ADVNULLANTENNA. What is proper way to change it?

Changing the antenna type - not done yet, will be in the next version.

**Comment by juffe84** [comment]
My version is Unicore_UM980 - R4.10Build11833. I think so that I can get it straight from unicore, but base stadion software use strsvr conversion. Can you get it also there when you use ntrip a service?

**Comment by Jef239** [comment]
I haven't tested version 11833, so I don't know what it can do that isn't documented. To get RTCM3, use "Rtcm tcp service" and connect to port 5016.

**Comment by Jef239** [comment]
I tested version 11833, 1013 packets are coming.

RTCM3: 1005=7 1006=7 1007=7 1013=7 1019=7 1020=7 1033=7 1042=7 1044=7 1045=7 1046=7 1077=7 1087=7 1097=7 1107=6 1117=7 1127=12 1137=6

**Comment by Jef239** [comment]
> Also I cant change antenna type ELT0123 to ADVNULLANTENNA. What is proper way to change it?

Done. v1.7.0
